<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/assets/models/dice.gltf --transform
Author: Seth Gardner (https://sketchfab.com/sethgardner)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-dice-model-d6-low-poly-4k-0603a7c54a6146a1b83df9a8cdb4b911
Title: Free Dice Model (D6) Low Poly 4K
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers, useTask } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { RigidBody as RapierRigidBody } from '@dimforge/rapier3d-compat';
	import { AutoColliders, RigidBody } from '@threlte/rapier';
	import { Mesh, Vector3 } from 'three';
	import { randFloat } from 'three/src/math/MathUtils.js';

	export let position: [number, number, number], launchAngle: number, launchSpeed: number;
	let dieMesh: Mesh;

	let rigidBody: RapierRigidBody;

	const { stop } = useTask(() => {
		if (rigidBody) {
			rigidBody.applyImpulse(
				new Vector3(launchSpeed * Math.cos(launchAngle), 2, launchSpeed * Math.sin(launchAngle)),
				true
			);
			rigidBody.applyTorqueImpulse(new Vector3(randFloat(-2, 2), 2, randFloat(-2, 2)), true);
			stop();
		}
	});

	export const ref = new Group();

	const gltf = useGltf('/assets/models/dice-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T.Group>
	<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
		{#await gltf}
			<slot name="fallback" />
		{:then gltf}
			<RigidBody bind:rigidBody>
				<AutoColliders shape={'cuboid'} mass={0.75}>
					<T.Mesh
						bind={dieMesh}
						castShadow
						{position}
						rotation={[randFloat(0, 360), randFloat(0, 360), randFloat(0, 360)]}
						geometry={gltf.nodes.redo_uv_Material001_0.geometry}
						material={gltf.materials['Material.001']}
					/>
				</AutoColliders>
			</RigidBody>
		{:catch error}
			<slot name="error" {error} />
		{/await}

		<slot {ref} />
	</T>
</T.Group>
