<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 src/lib/3d/models/scene.gltf --transform
Author: gabrieljuan0322 (https://sketchfab.com/gabrieljuan0322)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-b94e6a6a8c564fee81c2d794da6c5712
Title: Nintendo Switch
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/assets/models/nintendo-switch-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<!-- The following mesh was not automatically generated: it was added to better fit the canvas -->
		<T.Mesh scale={[3, 3, 3]} position={[-29, 1, 0]}>
			<T.Group position={[11.4, -0.36, 0.28]} rotation={[-0.01, -0.16, 0]}>
				<T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.blue_pad} />
				<T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.red_pad} />
				<T.Mesh
					geometry={gltf.nodes.Object_10.geometry}
					material={gltf.materials['Material.001']}
				/>
			</T.Group>
			<T.Group position={[9.64, -1.13, 0]} rotation={[3.13, 0.16, 0]} scale={0.05}>
				<T.Mesh geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.base_black} />
				<T.Mesh
					geometry={gltf.nodes.Object_21.geometry}
					material={gltf.materials.metal_yellow_pin}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_22.geometry}
					material={gltf.materials.type_c_cylinder}
				/>
			</T.Group>
			<T.Mesh
				geometry={gltf.nodes.Object_4.geometry}
				material={gltf.materials.vol_buttton}
				position={[11.21, 0.39, 0.24]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_6.geometry}
				material={gltf.materials.airflow}
				position={[10.16, 0.55, 0.07]}
				rotation={[-0.01, -0.16, 0]}
				scale={[0.05, 0.04, 0.05]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_12.geometry}
				material={gltf.materials.stand}
				position={[10.8, -0.63, 0.05]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_14.geometry}
				material={gltf.materials.red_pad}
				position={[9.66, -0.06, -0.14]}
				rotation={[1.56, 0, 0.16]}
				scale={[1.65, 1.68, 1.75]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_16.geometry}
				material={gltf.materials.bsk_speaker}
				position={[9.65, -1.02, -0.07]}
				rotation={[1.56, 0, 0.16]}
				scale={0.04}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_18.geometry}
				material={gltf.materials.screw}
				position={[9.64, -1.18, 0]}
				rotation={[3.13, 0.16, 0]}
				scale={0.02}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_24.geometry}
				material={gltf.materials['Material.006']}
				position={[9.64, -0.31, 0]}
				rotation={[-0.01, -0.16, 0]}
				scale={[1.01, 1, 1]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_26.geometry}
				material={gltf.materials.jack_port}
				position={[10.57, 0.46, 0.14]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_28.geometry}
				material={gltf.materials.pad_rail}
				position={[11.09, -0.23, 0.25]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_30.geometry}
				material={gltf.materials.material_0}
				position={[11.08, -0.28, 0.25]}
				rotation={[-0.01, -0.16, -1.57]}
				scale={[0.32, 0.26, 0.32]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_32.geometry}
				material={gltf.materials.material_0}
				position={[11.37, 0.05, 0.42]}
				rotation={[1.56, 0, 0.16]}
				scale={0.13}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_34.geometry}
				material={gltf.materials.dpad_logo}
				position={[7.88, -0.51, -0.15]}
				rotation={[-1.58, 0, 2.98]}
				scale={0.23}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_36.geometry}
				material={gltf.materials.power_logo}
				position={[8.48, 0.58, -0.19]}
				rotation={[-0.01, -0.16, 0]}
				scale={0.02}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_38.geometry}
				material={gltf.materials.body_01}
				position={[10.81, 0.55, 0.13]}
				rotation={[-0.01, -0.16, 0]}
				scale={[1.01, 1, 1]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_40.geometry}
				material={gltf.materials.blue_pad}
				position={[9.66, -0.06, -0.14]}
				rotation={[1.56, 0, 0.16]}
				scale={[1.65, 1.68, 1.75]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_42.geometry}
				material={gltf.materials.power_logo}
				position={[8.76, 0.59, -0.14]}
				rotation={[-0.01, -0.16, 0]}
				scale={0.01}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_44.geometry}
				material={gltf.materials.cube_screen}
				position={[9.66, -0.29, 0.03]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_46.geometry}
				material={gltf.materials['Material.009']}
				position={[9.66, -0.29, 0.03]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_48.geometry}
				material={gltf.materials.cube_screen_glass}
				position={[9.66, -0.29, 0.03]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_50.geometry}
				material={gltf.materials.analog}
				position={[7.87, 0.11, -0.14]}
				rotation={[1.56, 0, 0.16]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_52.geometry}
				material={gltf.materials.vol_buttton}
				position={[7.97, -0.7, -0.16]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_54.geometry}
				material={gltf.materials.vol_buttton}
				position={[9.63, 0.51, 0.01]}
				rotation={[-0.01, -0.16, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_56.geometry}
				material={gltf.materials.vol_buttton}
				position={[8.59, 0.56, -0.17]}
				rotation={[-0.01, -0.16, 0]}
				scale={[0.04, 0.02, 0.04]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_58.geometry}
				material={gltf.materials.vol_buttton}
				position={[9.66, 0.4, -0.15]}
				rotation={[1.56, 0, 0.16]}
				scale={[1.65, 1.68, 1.75]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_60.geometry}
				material={gltf.materials.dpad_logo}
				position={[11.27, -0.7, 0.39]}
				rotation={[1.56, 0, 0.16]}
				scale={0.06}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_62.geometry}
				material={gltf.materials.vol_buttton}
				position={[7.74, -0.37, -0.15]}
				rotation={[1.56, 0, 0.16]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_64.geometry}
				material={gltf.materials.vol_buttton}
				position={[11.22, 0.12, 0.42]}
				rotation={[1.56, 0, 0.16]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_66.geometry}
				material={gltf.materials.vol_buttton}
				position={[9.63, 0.5, 0.01]}
				rotation={[-0.01, -0.16, 0]}
			/>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
